name: Update S3 Bucket on Change

on:
  push:
    branches:
      - main  # Replace 'main' with your target branch

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      # Sync files to S3 bucket
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --exclude "*" --include "*.html" --include "*.css" --include "*.js"
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      # Sync files to S3 bucket
      # Step 4: Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
